### ISSUE TITLE
`ValueError: File cannot be found: V` for cluster

### ISSUE THREAD

**Issue by hugobuddel** [AstarVienna/ScopeSim_Templates#30]
These lines in `clusters.py` cause quite some warnings that the file `V` cannot be found:

https://github.com/AstarVienna/ScopeSim_Templates/blob/dc42d529bd88009d73d37477a39d950112a4b4f5/scopesim_templates/stellar/clusters.py#L86-L87

In particular, it raises an error when `!SIM.file.error_on_missing_file` is true:
```
Traceback (most recent call last):
  File "/builds/micado/micadowise/notebooks/FullStandardImaging.py", line 255, in <module>
    science3.make_simulation()
  File "/builds/micado/micadowise/src/micado/main/RawExtra.py", line 106, in make_simulation
    src = src_function()
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/scopesim_templates/calibration/micado/cluster.py", line 7, in cluster
    return scopesim_templates.stellar.clusters.cluster(mass=10000, distance=2000, core_radius=.1)
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/astropy/utils/decorators.py", line 546, in wrapper
    return function(*args, **kwargs)
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/scopesim_templates/stellar/clusters.py", line 82, in cluster
    spectra = [tcu.scale_spectrum(spec, "V", 0*u.mag) for spec in spectra]
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/scopesim_templates/stellar/clusters.py", line 82, in <listcomp>
    spectra = [tcu.scale_spectrum(spec, "V", 0*u.mag) for spec in spectra]
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/scopesim/effects/ter_curves_utils.py", line 302, in scale_spectrum
    filt = get_filter(filter_name)
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/scopesim/effects/ter_curves_utils.py", line 168, in get_filter
    path = find_file(filter_name, silent=True)
  File "/home/micado/.conda/envs/micadowise/lib/python3.10/site-packages/scopesim/utils.py", line 573, in find_file
    raise ValueError(msg)
ValueError: File cannot be found: V
```

There is a `V.dat` in `LFOA/filters`, but the error remains when adding that directory to `scopesim.rc.__search_path__` because the `.dat` is not appended.

Is it possible to prevent this warning / error?

**Comment by miguelverdugo** [comment]
Hi Hugo, 

In the new master branch (soon in pypi too) the problem should be solved. Any filter in the SVO database should be available as well as in the speXtra database where I also placed MICADO, METIS and other ESO filters.

**Comment by teutoburg** [comment]
I revisited the current status of this:

https://github.com/AstarVienna/ScopeSim_Templates/blob/1152838b076ca04f15001cacf2c55587c830816d/scopesim_templates/stellar/clusters.py#L93-L97

Running this will produce a all-`None` list for `spectra`. This is also in the final returned `Source` object's `.spectra` attribute. Meaning this `cluster()` function is currently still broken.

To check that this is not just somehow my configuration of things, I ran https://github.com/AstarVienna/ScopeSim_Templates/blob/1152838b076ca04f15001cacf2c55587c830816d/docs/notebooks/stellar.ipynb on a different machine, and in code cell 3, `src.spextra` indeed outputs a list of just `None`s.

As I started looking into `spextra` anyway recently, I'll try to figure out what's happening here...
